import type { Subscription } from "@/lib/stores/subscription-store"
import type { Payment } from "@/lib/stores/payment-store"
import type { Coupon } from "@/lib/stores/coupon-store"
import type { Notification } from "@/lib/stores/notification-store"

export function generateMockData() {
  // Generate mock subscriptions
  const subscriptions: Subscription[] = [
    {
      id: "sub_1",
      customerName: "John Doe",
      customerEmail: "john@example.com",
      planName: "Basic Plan",
      planId: "plan_basic",
      price: 9.99,
      billingCycle: "monthly",
      startDate: "2023-01-15",
      nextBillingDate: "2023-12-15",
      status: "active",
    },
    {
      id: "sub_2",
      customerName: "Jane Smith",
      customerEmail: "jane@example.com",
      planName: "Premium Plan",
      planId: "plan_premium",
      price: 19.99,
      billingCycle: "monthly",
      startDate: "2023-02-10",
      nextBillingDate: "2023-12-10",
      status: "active",
    },
    {
      id: "sub_3",
      customerName: "Bob Johnson",
      customerEmail: "bob@example.com",
      planName: "Enterprise Plan",
      planId: "plan_enterprise",
      price: 49.99,
      billingCycle: "monthly",
      startDate: "2023-03-05",
      nextBillingDate: "2023-12-05",
      status: "canceled",
    },
    {
      id: "sub_4",
      customerName: "Alice Brown",
      customerEmail: "alice@example.com",
      planName: "Basic Plan",
      planId: "plan_basic",
      price: 9.99,
      billingCycle: "monthly",
      startDate: "2023-04-20",
      nextBillingDate: "2023-12-20",
      status: "active",
    },
    {
      id: "sub_5",
      customerName: "Charlie Wilson",
      customerEmail: "charlie@example.com",
      planName: "Premium Plan",
      planId: "plan_premium",
      price: 19.99,
      billingCycle: "monthly",
      startDate: "2023-05-15",
      nextBillingDate: "2023-12-15",
      status: "active",
    },
  ]

  // Generate mock payments
  const payments: Payment[] = [
    {
      id: "pay_1",
      customerName: "John Doe",
      customerEmail: "john@example.com",
      subscriptionId: "sub_1",
      description: "Basic Plan - Monthly Subscription",
      amount: 9.99,
      date: "2023-11-15",
      dueDate: "2023-11-15",
      status: "paid",
    },
    {
      id: "pay_2",
      customerName: "Jane Smith",
      customerEmail: "jane@example.com",
      subscriptionId: "sub_2",
      description: "Premium Plan - Monthly Subscription",
      amount: 19.99,
      date: "2023-11-10",
      dueDate: "2023-11-10",
      status: "paid",
    },
    {
      id: "pay_3",
      customerName: "Bob Johnson",
      customerEmail: "bob@example.com",
      subscriptionId: "sub_3",
      description: "Enterprise Plan - Monthly Subscription",
      amount: 49.99,
      date: "2023-11-05",
      dueDate: "2023-11-05",
      status: "paid",
    },
    {
      id: "pay_4",
      customerName: "Alice Brown",
      customerEmail: "alice@example.com",
      subscriptionId: "sub_4",
      description: "Basic Plan - Monthly Subscription",
      amount: 9.99,
      date: "2023-11-20",
      dueDate: "2023-11-20",
      status: "paid",
    },
    {
      id: "pay_5",
      customerName: "Charlie Wilson",
      customerEmail: "charlie@example.com",
      subscriptionId: "sub_5",
      description: "Premium Plan - Monthly Subscription",
      amount: 19.99,
      date: "2023-11-15",
      dueDate: "2023-11-15",
      status: "paid",
    },
    {
      id: "pay_6",
      customerName: "John Doe",
      customerEmail: "john@example.com",
      subscriptionId: "sub_1",
      description: "Basic Plan - Monthly Subscription",
      amount: 9.99,
      date: "",
      dueDate: "2023-12-15",
      status: "pending",
    },
    {
      id: "pay_7",
      customerName: "Jane Smith",
      customerEmail: "jane@example.com",
      subscriptionId: "sub_2",
      description: "Premium Plan - Monthly Subscription",
      amount: 19.99,
      date: "",
      dueDate: "2023-12-10",
      status: "pending",
    },
    {
      id: "pay_8",
      customerName: "Alice Brown",
      customerEmail: "alice@example.com",
      subscriptionId: "sub_4",
      description: "Basic Plan - Monthly Subscription",
      amount: 9.99,
      date: "",
      dueDate: "2023-12-20",
      status: "pending",
    },
    {
      id: "pay_9",
      customerName: "Charlie Wilson",
      customerEmail: "charlie@example.com",
      subscriptionId: "sub_5",
      description: "Premium Plan - Monthly Subscription",
      amount: 19.99,
      date: "",
      dueDate: "2023-12-15",
      status: "pending",
    },
  ]

  // Generate mock coupons
  const coupons: Coupon[] = [
    {
      id: "coup_1",
      code: "WELCOME10",
      description: "10% off for new customers",
      discountType: "percentage",
      discountValue: 10,
      validFrom: "2023-01-01",
      validUntil: "2023-12-31",
      active: true,
      usageLimit: 100,
      usageCount: 45,
    },
    {
      id: "coup_2",
      code: "SUMMER20",
      description: "20% off summer promotion",
      discountType: "percentage",
      discountValue: 20,
      validFrom: "2023-06-01",
      validUntil: "2023-08-31",
      active: false,
      usageLimit: 200,
      usageCount: 150,
    },
    {
      id: "coup_3",
      code: "FLAT5",
      description: "$5 off any subscription",
      discountType: "fixed",
      discountValue: 5,
      validFrom: "2023-01-01",
      validUntil: "2023-12-31",
      active: true,
      usageLimit: 500,
      usageCount: 320,
    },
    {
      id: "coup_4",
      code: "PREMIUM25",
      description: "25% off Premium Plan",
      discountType: "percentage",
      discountValue: 25,
      validFrom: "2023-10-01",
      validUntil: "2023-12-31",
      active: true,
      usageLimit: 100,
      usageCount: 12,
    },
    {
      id: "coup_5",
      code: "BLACKFRIDAY",
      description: "30% off Black Friday special",
      discountType: "percentage",
      discountValue: 30,
      validFrom: "2023-11-24",
      validUntil: "2023-11-27",
      active: true,
      usageLimit: 300,
      usageCount: 0,
    },
  ]

  // Generate mock notifications
  const notifications: Notification[] = [
    {
      id: "notif_1",
      message: "Your subscription will renew in 3 days",
      type: "info",
      date: "2023-11-12",
      read: false,
    },
    {
      id: "notif_2",
      message: "Payment successful for Premium Plan",
      type: "success",
      date: "2023-11-10",
      read: true,
    },
    {
      id: "notif_3",
      message: "New coupon BLACKFRIDAY is now available",
      type: "info",
      date: "2023-11-24",
      read: false,
    },
    {
      id: "notif_4",
      message: "Your subscription has been updated",
      type: "info",
      date: "2023-11-05",
      read: true,
    },
    {
      id: "notif_5",
      message: "Payment failed. Please update your payment method",
      type: "error",
      date: "2023-11-01",
      read: true,
    },
  ]

  return {
    subscriptions,
    payments,
    coupons,
    notifications,
  }
}

